version: 0.2
env:
  secrets-manager:
    LOGIN: SonarSecret:sonartoken
    HOST: SonarSecret:HOST
    Organization: SonarSecret:Organization
    Project: SonarSecret:Project

phases:
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/Hello-4.0.0.war
    - appspec.yml
  discard-paths: yes
